let express = require("express")
let rt = express.Router()
let {reg,login, doc, allusr, deluser, alldr} = require("../controllers/controller")
let {appoint, book, getappoint, updateappoint, getpat, recapp, getallappoint, delappoint, getallpenappoint} = require("../controllers/appointcon")
const { createprec, getprec, docprec, getallprec } = require("../controllers/precriptioncon")
const { recaddpat, patdet, patdetdoc, updateappoints } = require("../controllers/recpatcon")
rt.post("/reg", reg)
rt.post("/login", login)
rt.get("/doc",doc)
rt.get("/myappoint/:pid",appoint)
rt.post("/bookappoint",book)
rt.get("/allappoint/:did",getappoint)
rt.post("/updateappoint",updateappoint)
rt.post("/updateappoints",updateappoints)
rt.get("/getpat/:did",getpat)
rt.post("/createprec",createprec)
rt.get("/getprec/:pid",getprec)
rt.get("/docprec/:did",docprec)
rt.get("/receptionpat",patdet)
rt.get("/receptionpat/:did",patdetdoc)
rt.post("/recaddpat",recaddpat)
rt.post("/receptionappoint",recapp)
rt.get("/allappoint",getallappoint)
rt.delete("/deleteappoint/:pid",delappoint)
rt.get("/allprec",getallprec)
rt.get("/allusr",allusr)
rt.get("/alldr",alldr)
rt.get("/deluser/:_id",deluser)
rt.get("/getpenapp",getallpenappoint)
module.exports = rt